config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :administrator
  resources :users
  resources :sketches, only: [:new, :create]

  delete ":username/:slug", to: "sketches#destroy", as: :sketch_delete
  get ":username/:slug/edit", to: "sketches#edit", as: :sketch_edit
  patch ":username/:slug", to: "sketches#update", as: :sketch_update
  get ":username/:slug", to: "sketches#show", as: :sketch_show
  get ":username", to: "sketches#index", as: :sketches_index

end

app/models/sketch.rb
class Sketch < ActiveRecord::Base

  belongs_to :user

  before_create :generate_slug

  validates :title, length: { minimum: 1 }, presence: true
  validates :body, presence: true

  default_scope { order("created_at DESC")}

  private

  def generate_slug
    self.slug = SecureRandom.hex(10)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable, :lockable

  has_many :sketches, dependent: :destroy

  validates :role, presence: true, inclusion: { in: %w{standard pro admin}, message: "should be one of admin, pro, standard" }
  validates :username, length: { minimum: 3}, presence: true
  validates :name, length: {minimum: 3}, presence: true

  def admin?
    role == "admin"
  end

  def pro?
    role == "pro"
  end

  def standard?
    role == "standard"
  end

  def upgradeable?
    self.standard?
  end

  def downgradeable?
    self.pro?
  end

  def upgrade_account
    if self.upgradeable?
      self.update_attributes(role: "pro")
    end
  end

  def downgrade_account
    if self.downgradeable?
      self.update_attributes(role: "standard")
    end
  end

  # downgradeable saved for users who do not pay the monthly fee. Their account will be downgraded. If users opt out of the monthly payment, they can also choose to downgrade their account.

end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController

  before_action :authenticate_user!

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_in_path_for(resource)
    new_sketch_path
  end

  protected

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action Dave."
    redirect_to root_url
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :username)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sketches_controller.rb
class SketchesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    user = User.find_by(username: params[:username])
    @sketches = user.sketches
  end

  def show
    user = User.find_by(username: params[:username])
    @sketch = user.sketches.find_by!(slug: params[:slug])
  end
  
  def new
    @sketch = current_user.sketches.new
    authorize @sketch
  end

  def create
    @sketch = current_user.sketches.build(sketch_params)
    authorize @sketch

    if @sketch.save
      flash[:notice] = "Sketch was saved."
      redirect_to sketches_index_path(current_user.username)
    else
      flash[:error] = "Wasn't saved Dave!"
      render :new
    end

  end

  def edit
    user = User.find_by(username: params[:username])
    @sketch = user.sketches.find_by!(slug: params[:slug])
    authorize @sketch
  end

  def update
    user = User.find_by(username: params[:username])
    @sketch = user.sketches.find_by!(slug: params[:slug])
    authorize @sketch

    if @sketch.update_attributes(sketch_params)
      flash[:notice] = "Sketch was updated."
      redirect_to sketches_index_path(current_user.username)
    else
      flash[:error] = "An error occurred when updating the sketch"
    end
  end

  def destroy
    user = User.find_by(username: params[:username])
    @sketch = user.sketches.find_by!(slug: params[:slug])
    authorize @sketch

    if @sketch.destroy
      flash[:notice] = "Your sketch has been deleted."
      redirect_to sketches_index_path(current_user.username)
    else
      flash[:error] = "There was an error deleting this sketch."
      render :show
    end
  end

  private

  def sketch_params
    permitted_attributes = [:title, :body]
    params.require(:sketch).permit(permitted_attributes)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
#sketch-view
  #code-editor.stretch
    .container-fluid
      .row
        #editor.index-page

  #code-results
    .container-fluid
      .row
        #buttons
          %button#submit-button.btn.btn-default{type: "button"} Run
          %button#clear-editor-button.btn.btn-default{type: "button"} Clear Editor
          %button#clear-console-button.btn.btn-default{type: "button"} Clear Console
        #results

:javascript
   var editor = ace.edit("editor");
   editor.setTheme("ace/theme/terminal");
   editor.getSession().setMode("ace/mode/ruby");
   editor.getSession().setTabSize(2);
   editor.setReadOnly(false);
   editor.getSession().setUseWrapMode(true);
   editor.setHighlightActiveLine(true);

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Welcome to RubyPlex
    %meta{"name" => "viewport", "content" => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    - if flash[:notice]
      .alert.alert-success
        %button.close{"data-dismiss" => "alert", type: "button"} ×
        = flash[:notice]
    - elsif flash[:error]
      .alert.alert-danger
        %button.close{"data-dimiss" => "alert", type: "button"} ×
        = flash[:error]
    - elsif flash[:alert]
      .alert.alert-warning
        %button.close{"data-dismiss" => "alert", type: "button"} ×
        = flash[:alert]
    %nav.navbar.navbar-default
      .navbar-header
      %ul.nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu
              %li{role: "presentation"}
                = link_to sketches_index_path(current_user.username) do
                  Sketches
                  %span.badge= current_user.sketches.count
              %li=link_to "New Sketch", new_sketch_path
              %li= link_to "Edit Profile", edit_user_registration_path
              - if current_user.admin?
                %li= link_to "Site Administration"
              %li.divider{role: "separator"}
              %li= link_to "Log Out", destroy_user_session_path, method: :delete
        - else
          .list-inline
            %li= link_to "Sign In", new_user_session_path
            |
            %li= link_to "Register", new_user_registration_path

    = yield

app/views/sketches/_form.html.haml
#sketch-view
  = form_for(sketch, url: url) do |f|
    #code-editor
      .container-fluid
        .row
          - if read_only
            = sketch.title
          - else
            = f.label :title
            = f.text_field :title, placeholder: "Sketch description ..."
          .editor.save-page
          = f.text_area :body, id: "input_value", class: "text-area"

    #code-results
      .container-fluid
        .row
          #buttons
            %button#submit-button.btn.btn-default{type: "button"} Run
            - if !read_only
              %button#clear-editor-button.btn.btn-default{type: "button"} Clear Editor
              %button#clear-console-button.btn.btn-default{type: "button"} Clear Console
              = f.submit "Save Sketch", class: "btn btn-default", onclick: "infoStore()"
          #results

:javascript
  var editor;
  var infoStore = function() {
    document.getElementById("input_value").value = editor.getValue();
  };
  $(document).ready(function() {
    // workaround from http://stackoverflow.com/questions/15662337/can-ace-editor-support-multiple-code-editors-in-one-page
    $('.editor').each(function() {
        editor = ace.edit(this);
        var textarea = $('textarea[id="input_value"]').hide();
        editor.getSession().setValue(textarea.val());
        editor.setTheme("ace/theme/terminal");
        editor.getSession().setMode("ace/mode/ruby");
        editor.getSession().setTabSize(2);
        editor.getSession().setUseWrapMode(true);
        editor.$blockScrolling = Infinity;
        editor.setReadOnly();
     });
  });

app/views/sketches/edit.html.haml
- if policy(@sketch).edit?
  = render partial: "form", locals: {sketch: @sketch, url: sketch_update_path(@sketch.user.username, @sketch.slug), read_only: false}

app/views/sketches/index.html.haml
%section#sketches.container-fluid
  .row
    .col-md-2
    .col-md-8
      - if @sketches.empty?
        No Sketches
      - else
        .total-sketches
          = "You currently have #{@sketches.count} sketches"
        - @sketches.each do |sketch|
          .panel.panel-default
            .panel-heading
              .panel-title
                Share link:
                - if policy(sketch).edit?
                  = link_to sketch_show_path(sketch.user.username, sketch.slug), sketch_edit_path(sketch.user.username, sketch.slug)
                  = link_to "Delete", sketch_delete_path(sketch.user.username, sketch.slug), method: :delete, class: "btn btn-danger glyphicon glyphicon-trash pull-right", id: "delete-sketch"
                - else
                  = link_to sketch_show_path(sketch.user.username, sketch.slug), sketch_show_path(sketch.user.username, sketch.slug)
            .panel-body
              = sketch.title
              %br
              Created
              = time_ago_in_words(sketch.created_at)
              ago
              %pre.editor
                = sketch.body

:javascript
  $(document).ready(function() {
    // workaround from http://stackoverflow.com/questions/15662337/can-ace-editor-support-multiple-code-editors-in-one-page
    var editor;
    $('.editor').each(function() {
        editor = ace.edit(this);
        editor.setTheme("ace/theme/terminal");
        editor.getSession().setMode("ace/mode/ruby");
        editor.getSession().setTabSize(2);
        editor.setReadOnly(true);
    });
  });

app/views/sketches/new.html.haml
- if @sketch.new_record? && policy(@sketch).create?
  = render partial: "form", locals: {sketch: @sketch, url: sketches_path, read_only: false}

app/views/sketches/show.html.haml
= render partial: "form", locals: {sketch: @sketch, url: sketch_show_path(@sketch.user.username, @sketch.slug), read_only: true}